CREATE TABLE RCLTBLS.CAM_SERVICE_CATEGORY_DTL(
  PK_SERVICE_CODE VARCHAR2(5),
  PK_FROM_DATE NUMBER(8),
  PK_TO_DATE NUMBER(8),
  SERVICE_CATEGORY VARCHAR2(1),
  RECORD_STATUS VARCHAR2(1),
  RECORD_ADD_DATE NUMBER(8),
  RECORD_ADD_TIME NUMBER(4),
  RECORD_ADD_USER VARCHAR2(10),
  RECORD_CHANGE_USER VARCHAR2(10),
  RECORD_CHANGE_DATE NUMBER(8),
  RECORD_CHANGE_TIME NUMBER(4)
)TABLESPACE RCLDATA;


GRANT SELECT, INSERT, UPDATE, DELETE ON RCLTBLS.CAM_SERVICE_CATEGORY_DTL TO SEALINER, VASAPPS WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCLTBLS.CAM_SERVICE_CATEGORY_DTL TO SEALINER_RW, VASAPPS;
GRANT SELECT, INSERT, UPDATE, DELETE ON RCLTBLS.CAM_SERVICE_CATEGORY_DTL TO RCLJOBS;
GRANT SELECT ON RCLTBLS.CAM_SERVICE_CATEGORY_DTL TO SEALINER_RO;