CREATE TABLE RCLTBLS.CAM_VENDOR_CATEGORY( 
PK_VENDOR_CODE VARCHAR2(10) NOT NULL,
PK_CATEGORY  VARCHAR2(1) NOT NULL, 
FK_LINE VARCHAR2(1),
FK_TRADE VARCHAR2(1),
FK_AGENT VARCHAR2(3),
LOCATION  VARCHAR2(5),
REMARKS VARCHAR2(80),
RECORD_ADD_USER VARCHAR2(10),
RECORD_ADD_DATE NUMBER(8),
RECORD_ADD_TIME NUMBER(4),
RECORD_CHANGE_USER VARCHAR2(10), 
RECORD_CHANGE_DATE NUMBER(8),   
RECORD_CHANGE_TIME NUMBER(4), 
RECORD_STATUS VARCHAR2(1),
BUSINESS_PARTNER_TYPE VARCHAR2(5)
) TABLESPACE RCLDATA ;



GRANT SELECT, INSERT, UPDATE, DELETE ON CAM_VENDOR_CATEGORY TO RCLJOBS, VASAPPS, SEALINER WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAM_VENDOR_CATEGORY TO SEALINER_RW, RCLAPPS;