CREATE TABLE RCLTBLS.CAM_LOCAL_LANGUAGE(
	PK_CODE VARCHAR2(4), 
	DESCRIPTION VARCHAR2(25),
	RECORD_ADD_USER  VARCHAR2(10),
	RECORD_ADD_DATE NUMBER(8),
	RECORD_ADD_TIME NUMBER(4),
	RECORD_CHANGE_USER VARCHAR2(4), 
	RECORD_CHANGE_DATE NUMBER(8), 
	RECORD_CHANGE_TIME NUMBER(4)
)TABLESPACE RCLDATA ;


/
GRANT SELECT ON RCLTBLS.CAM_LOCAL_LANGUAGE to RCLAPPS WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON RCLTBLS.CAM_LOCAL_LANGUAGE to RCLJOBS, RCLTBLS, SEALINER, VASAPPS WITH GRANT OPTION;
/