CREATE OR REPLACE TRIGGER RCLTBLS.TRG_VALIDATE_VENDOR_CODE
BEFORE INSERT OR UPDATE ON CAM_VENDOR_CATEGORY
FOR EACH ROW
DECLARE
 v_count NUMBER;
BEGIN
  IF INSERTING OR UPDATING('FK_VENDOR_CODE') THEN
     IF TRIM(:NEW.PK_VENDOR_CODE) IS NOT NULL THEN
     SELECT COUNT(1) INTO v_count FROM RCLTBLS.CAM_VENDOR WHERE PK_VENDOR_CODE = :NEW.PK_VENDOR_CODE AND RECORD_STATUS IN ('A', 'N', 'P', 'E') ; 
	  
        IF v_count <= 0 THEN
        RAISE_APPLICATION_ERROR(-20042, '~tvcvncd~t' || fnc_get_message(-20042) || '~t');
        END IF;
     END IF;
  END IF;
END;