CREATE OR REPLACE FORCE EDITIONABLE VIEW SEALINER.SERVICE_CATEGORY_DTL(SERVICE_CODE,FROM_DATE,TO_DATE,SERVICE_CATEGORY,XXRCST,RECORD_ADD_DATE,RECORD_ADD_TIME,RECORD_ADD_USER,RECORD_CHANGE_USER,RECORD_CHANGE_DATE,RECORD_CHANGE_TIME)
AS
  SELECT PK_SERVICE_CODE, PK_FROM_DATE, PK_TO_DATE, SERVICE_CATEGORY,RECORD_STATUS,RECORD_ADD_DATE,RECORD_ADD_TIME,RECORD_ADD_USER,RECORD_CHANGE_USER,RECORD_CHANGE_DATE,RECORD_CHANGE_TIME
  FROM RCLTBLS.CAM_SERVICE_CATEGORY_DTL;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON SEALINER.SERVICE_CATEGORY_DTL TO SEALINER_RW, VASAPPS WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEALINER.SERVICE_CATEGORY_DTL TO RCLJOBS;
GRANT SELECT ON SEALINER.SERVICE_CATEGORY_DTL TO SEALINER_RO;
