
CREATE OR REPLACE FORCE EDITIONABLE VIEW SEALINER.VENDOR_CATEGORY(VCVNCD,CATEGORY,AGENT_LEVEL_1,AGENT_LEVEL_2,AGENT_LEVEL_3,LOCATION,REMARKS,RECORD_ADD_USER,RECORD_ADD_DATE,RECORD_ADD_TIME,RECORD_CHANGE_USER,RECORD_CHANGE_DATE,RECORD_CHANGE_TIME,VCRCST,BUSINESS_PARTNER_TYPE)
AS
  SELECT PK_VENDOR_CODE,
    PK_CATEGORY,
    FK_LINE,
    FK_TRADE,
    FK_AGENT,
    LOCATION,
    REMARKS,
    RECORD_ADD_USER,
    RECORD_ADD_DATE,
    RECORD_ADD_TIME,
    RECORD_CHANGE_USER,
    RECORD_CHANGE_DATE,
    RECORD_CHANGE_TIME,
    RECORD_STATUS,
    BUSINESS_PARTNER_TYPE
  FROM RCLTBLS.CAM_VENDOR_CATEGORY;
/ 
GRANT SELECT, INSERT, UPDATE, DELETE ON SEALINER.VENDOR_CATEGORY TO RCLJOBS, VASAPPS, SEALINER WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON SEALINER.VENDOR_CATEGORY TO SEALINER_RW, RCLAPPS;

